### ISSUE TITLE
[hint-compat-api] Suppress duplicate reports for prefixed properties by CSS rule block

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1676]
*From [discussions in #1614](https://github.com/webhintio/hint/pull/1614#pullrequestreview-191883554)*

For consistency I think we need to keep suppression of double-reports for prefixed properties independent of the order in which the properties are listed. So long as the unprefixed version appears in the same CSS rule block, let's not flag the prefixed versions.

With that in mind, currently this works as expected:

```css
.example {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
}
```

This should not flag the prefixed versions, but currently does:

```css
.example {
    appearance: none;
    -webkit-appearance: none;
    -moz-appearance: none;
}
```

And this should flag the prefixed versions, but currently doesn't:

```css
.example1 {
    -webkit-appearance: none;
    -moz-appearance: none;
}

.example2 {
    appearance: none;
}
```
