### ISSUE TITLE
Deprecated vendor prefixes in reverse order reports an error

### ISSUE THREAD

**Issue by antross** [webhintio/hint#1827]
When deprecated vendor prefixes are involved, reversing the order of the properties still causes the compat hint to incorrectly raise an issue:
```css
.example {
  transition:all .2s ease-in-out;
  -o-transition:all .2s ease-in-out;
}
```
Expected:
(no reported issues)

Actual:
```
transition prefixed with -o- is not supported by opera 57.
```

_Originally posted by @antross in https://github.com/webhintio/hint/pull/1820#issuecomment-460449277_
