### ISSUE TITLE
[Feature] Compat-API should not flag issues if code is in @supports

### ISSUE THREAD

**Issue by molant** [webhintio/hint#1869]
# 🚀 Feature request

## Description

Right now the compat-api for CSS doesn't check if a feature is being featured detected previously via `@supports` and thus causing false positives.

The hint should be aware of those.

## What scenarios will this solve?

Flagging false positives when users run the compat.

**Comment by sarvaje** [comment]
@webhintio/core I think I need a little bit more explanation here. Do we want to ignore completely the `@support` block?
If we have a CSS like this, what should the `hint` check?:

```css
@supports (display: flex) {
    .content {
        display: flex;
        align-items: center;
        justify-content: center;
    }
}

html,
body {
    padding: 0;
    margin: 0;
    height: 100%;
    width: 100%;
}

.content {
    background-color: #777;
    color: #000;
    height: 100%;
    width: 100%;
}

p {
    margin: 0;
}
```

Also, what happen when a browser doesn't support `@supports` should the `hint` ignore it?

**Comment by molant** [comment]
I think the idea is:
- If a browser doesn't support a property:
  - If it supports `@supports` check if it is in a block that checks for it
  - If it doesn't support `@supports`, ignore that block entirely

So with your flexbox example and looking into the [MDN data](https://developer.mozilla.org/en-US/docs/Web/CSS/flex#Browser_compatibility):
- IE10 shouldn't show any problem even though it only supports the prefixed version because it doesn't have `@supports`

A better example will be [`grid`](https://developer.mozilla.org/en-US/docs/Web/CSS/grid#Browser_compatibility):
- Edge 13+ has `@supports`
- Edge 16+ has `grid`, previous versions had only the prefixed version

If someone did something attrocious like:

```css
@supports (display: flex) {
    .content {
        display: grid;
        ...
    }
}
```

This should be a problem in Edge 15 and lower but not 16.



IIRC full support with no prefixes was added in Edge 16. Edge 13 supported `@supports`
