### ISSUE TITLE
[Question] should hint `compat-api` report unknown properties?

### ISSUE THREAD

**Issue by sarvaje** [webhintio/hint#1995]
For this CSS:
```css
.content {
    color: red;
    unknownProperty: anyvalue;
}
```

should the hint report the property `unknownProperty`?
