### ISSUE TITLE
[Bug] @supports in `hint-compat-api` ignores all browsers if one is unsupported

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2517]
Repro:
```css
/* Target browsers `['chrome 74', 'edge 16', 'firefox 65', 'ie 10']` */
@supports (display: grid) {
    -webkit-appearance: button; /* Not flagged as entire block is ignored due to 'ie 10' */
}
```
