### ISSUE TITLE
[Bug] Formatting is incorrect for some CSS code snippets

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2597]
Examples from running the browser extension against https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary:

Actual:
```css
@charset "UTF-8" { }
```

Expected:
```css
@charset "UTF-8";
```

Actual:
```css
@media all and (min-width:29.9385em) {
    @supports (display:flex) {
        .document-head .center .document-actions {
        flex-grow: 9999;
    }
    }
}
```

Expected:
```css
@media all and (min-width:29.9385em) {
    @supports (display:flex) {
        .document-head .center .document-actions {
            flex-grow: 9999;
        }
    }
}
```
