### ISSUE TITLE
Create documentation for Circle CI

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2713]
Need to copy paste on a markdown file and put it on the hint repo.

- - - - - - - - -

Specifically this should include example Circle CI configurations demonstrating how to use webhint.

**Comment by sarvaje** [comment]
As in [`travis`](https://github.com/webhintio/hint/issues/2776#issuecomment-520580266), for CircleCI we just need to follow these steps:
1. Install webhint as a devDependency - `npm install hint --save-dev`
1. Add to your current `test` script in your `package.json` ` && hint ./`
1. Add the file `.circleci/config.yml` with this configuration:

```yml
version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:10.16.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: npm install
      - run: npm run test
```

Until https://github.com/webhintio/hint/pull/2800 is merged and published, the step 1 should be `npm install hint @hint/configuration-development --save-dev`, and you should create a .hintrc in his project extending `development`

```json
{
    "extends": ["development"]
}
```

**Comment by sarvaje** [comment]
I'm adding a list of scenarios we want to consider for the documentation:

Here is a initial list, please, feel free to update the list:

#### Scanning the project locally

- [ ] Webhint is not part of the project (Maybe the project is not nodejs)
- [ ] Webhint in the package json.

#### Scanning the project "online" (for example, pre-production)

- [ ] Webhint is not part of the project (Maybe the project is not nodejs)
- [ ] Webhint in the package json.

#### Common
- [ ] Using custom `.hintrc`.
- [ ] Enabling telemetry.

@webhintio/core ideas?

**Comment by sarvaje** [comment]
## Locally

### Webhint is in the package.json

Run in your project.
```Shell
npm install hint --save--dev
```

In the file `package.json` add a new script `test-hint`:
```json5
...
"scripts": {
    ...
    "test-hint": "hint ./" // ./ or the path where the files to test are.
  }
...
```

Add the file `.circleci/config.yml` to your project:
```yml
version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:lts
    steps:
      - checkout # check out the code in the project directory
      - run: npm install
      - run: npm run test-hint
```

>Note: In this case `hint` will use as default configuration `configuration-development` if a `.hintrc` file is not present.

### Project in another language or not included in the package.json

When your project is not a `nodejs` project or you just doesn't want to/can modify your `package.json` you can do:

Add a `.circleci/config.yml` to your project:
```yml
version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:latest-node
    steps:
      - checkout # check out the code in the project directory
      - run: npm install hint --no-save
      - run: node node_modules/hint/dist/src/bin/hint.js ./ # ./ or the path where the files to test are.
```

>In this case, we need `nodejs` to be install in the image. For the built-in images in circleci, you just need to add `-node` to the image tag, if you are using your own image, you need to update it to include `nodejs`. Once we have node in the image, we can install `hint` manually and run the scan.

As in the previous example, the default configuration will be `configuration-development`.

## Online

### Webhint is in the package.json

Run in your project.
```Shell
npm install hint --save--dev
```

In the file `package.json` add a new script `test-hint`:
```json5
...
"scripts": {
    ...
    "test-hint": "hint https://url-to-your-project" // ideally, this url will be to your staging/preproduction environment.
}
...
```

Add the file `.circleci/config.yml` to your project:
```yml
version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:lts-browsers
    steps:
      - checkout # check out the code in the project directory
      # Add the necessary steps to deploy your website.
      - run: npm install
      - run: npm run test
```

>Note: In this case `hint` will use as default configuration `configuration-web-recommended` if a `.hintrc` file is not present.

>Note: `configuration-web-recommended` use by default the connector `puppeteer` which requires a "chromium" browser to work. In you are using a `circleci` built-in image, you just need to add `-browsers` to the tag to have browsers installed. If you are using you custom image, you need to install a chromium browser in your image first.

### Project in another language or hint not included in the package.json

When your project is not a `nodejs` project or you just doesn't want to/can modify your `package.json` you can do:

Add the file `.circleci/config.yml` to your project:
```yml
version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:latest-node-browsers
    steps:
      - checkout # check out the code in the project directory
      # Add the necessary steps to deploy your website.
      - run: npm install hint --no-save
      - run: node node_modules/hint/dist/src/bin/hint.js https://url-to-your-project
```

>The default configuration in this case will be `configuration-web-recommended`

>As you can notice, if you need `nodejs` + browsers in your circleci image, you just need to add `-node-browsers` to the image tag. If you are using a custom image, you will need to install node and a chromium browser in you image.

## Common

### Enabling telemetry

To enabling telemetry you have a couple of options:
1. By parameter. You need to add the parameter to the script to your `package.json`
    ```json
    …
    "scripts": {
        …
        "test-hint": "hint https://webhint.io --debug --tracking=on"
      },
    …
    ```
    or in you `.circleci/config.yml`:
    ```yml
    version: 2.1
    jobs:
      build:
        docker: 
          - image: circleci/python:latest-node-browsers
        steps:
          - checkout # check out the code in the project directory
          # Add the necessary steps to deploy your website.
          - run: npm install hint --no-save
          - run: node node_modules/hint/dist/src/bin/hint.js https://url-to-your-project --tracking=on
    ```
1. By env variable. You need to configure the env variable `HINT_TRACKING` in your file `.circleci/config.yml`:
    ```yml
    version: 2.1
    jobs:
      build:
        docker: 
          - image: circleci/node:lts-browsers
        steps:
          - checkout # check out the code in the project directory
          - run: echo 'export HINT_TRACKING="on"' >> $BASH_ENV
          - run: npm install
          - run: npm run test-hint
    ```
