### ISSUE TITLE
Create documentation for Travis CI

### ISSUE THREAD

**Issue by antross** [webhintio/hint#2776]
Need to copy paste on a markdown file and put it on the hint repo.

- - - - - - - - -

Specifically this should include example Travis CI configurations demonstrating how to use webhint.

**Comment by molant** [comment]
FYI, there's already https://webhint.io/docs/user-guide/development-flow-integration/travis-and-azure/

________________________________

**Comment by antross** [comment]
Thanks for the pointer. Definitely something we should look at with respect to this. I'm hoping we can produce something that's a bit more bite-sized as a "quick start" if you will, but maybe I'm being too optimistic. 😊

**Comment by sarvaje** [comment]
If we want to have a more simple documentation about how to run webhint for static files, we just need to mention:
1. Install webhint as a devDependency - `npm install hint --save-dev`
1. Add to your current `test` script in your `package.json` ` && hint ./`

Until https://github.com/webhintio/hint/pull/2800 is merged, the step 1 should be `npm install hint @hint/configuration-development --save-dev`, and you should create a .hintrc in his project extending `development`

```json
{
    "extends": ["development"]
}
```

**Comment by sarvaje** [comment]
I'm adding a list of scenarios we want to consider for the documentation:

Here is a initial list, please, feel free to update the list:

#### Scanning the project locally

- [ ] Webhint is not part of the project (Maybe the project is not nodejs)
- [ ] Webhint in the package json.

#### Scanning the project "online" (for example, pre-production)

- [ ] Webhint is not part of the project (Maybe the project is not nodejs)
- [ ] Webhint in the package json.

#### Common
- [ ] Using custom `.hintrc`.
- [ ] Enabling telemetry.

@webhintio/core ideas?

**Comment by antross** [comment]
Those sound good to me. @hxlnt what do you think?

When using a `.hintrc` we'll probably want to call out which configuration we recommend extending too.
* Scanning the project locally - `"extends": ["development"]`
* Scanning the project "online" - `"extends": ["web-recommended"]`

**Comment by hxlnt** [comment]
What about an explicit callout regarding report generation and gating?

**Comment by sarvaje** [comment]
## Locally

### Webhint is in the package.json

Run in your project.
```Shell
npm install hint --save--dev
```

In the file `package.json` add a new script `test-hint`:
```json5
...
"scripts": {
    ...
    "test-hint": "hint ./" // ./ or the path where the files to test are.
  }
...
```

Add the file `.travis.yml` to your project:
```yml
language: node_js
node_js:
- 10.16.2

script:
  - npm install
  - npm run test-hint
```

>Note: In this case `hint` will use as default configuration `configuration-development` if a `.hintrc` file is not present.

### Project in another language or not included in the package.json

When your project is not a `nodejs` project or you just doesn't want to/can modify your `package.json` you can do:

Add a `.travis.yml` to your project:
```yml
language: python

before_install:
- nvm install node

script:
  - npm install hint --no-save
  - node node_modules/hint/dist/src/bin/hint.js ./ # ./ or the path where the files to test are.
```

>Travis CI includes node and npm by default in the languages I have tried, but an old version, so I recommend to install it manually (as we indicate in the file `.travis.yml`).

As in the previous example, the default configuration will be `configuration-development`.

## Online

### Webhint is in the package.json

Run in your project.
```Shell
npm install hint --save--dev
```

In the file `package.json` add a new script `test-hint`:
```json5
...
"scripts": {
    ...
    "test-hint": "hint https://url-to-your-project" // ideally, this url will be to your staging/preproduction environment.
}
...
```

Add the file `.travis.yml` to your project:
```yml
language: node_js
node_js:
- 10.16.2

addons:
  chrome: stable

script:
  - npm install
  - npm run test
```

>Note: In this case `hint` will use as default configuration `configuration-web-recommended` if a `.hintrc` file is not present.

>Note: `configuration-web-recommended` use by default the connector `puppeteer` which requires a "chromium" browser to work. As you can notice, we are indicating to Travis CI to install `chrome` in our test environment.

### Project in another language or hint not included in the package.json

When your project is not a `nodejs` project or you just doesn't want to/can modify your `package.json` you can do:

Add the file `.travis.yml` to your project:
```yml
language: python

addons:
  chrome: stable

before_install:
- nvm install node

script:
   # Add the necessary steps to deploy your website.
  - npm install hint --no-save
  - node node_modules/hint/dist/src/bin/hint.js https://url-to-your-project
```

>The default configuration in this case will be `configuration-web-recommended`

>In this case, we are telling to Travis CI to install `chrome` and `nodejs`.

## Common

### Enabling telemetry

To enabling telemetry you have a couple of options:
1. By parameter. You need to add the parameter to the script to your `package.json`
    ```json
    …
    "scripts": {
        …
        "test-hint": "hint https://webhint.io --debug --tracking=on"
      },
    …
    ```
    or in you `.circleci/config.yml`:
    ```yml
    language: python

    addons:
      chrome: stable

    before_install:
    - nvm install node

    script:
       # Add the necessary steps to deploy your website.
      - npm install hint --no-save
      - node node_modules/hint/dist/src/bin/hint.js https://url-to-your-project --tracking=on
    ```
1. By env variable. You need to configure the env variable `HINT_TRACKING` in your file `.travis.yml`:
    ```yml
    language: node_js
    node_js:
    - 10.16.2

    addons:
      chrome: stable

    env:
      - HINT_TRACKING=on

    script:
      - npm install
      - npm run test-hint
    ```

About how to use your custom `.hintrc` file, I think we should link to the documentation where we talk about it.
