### ISSUE TITLE
[Bug] "CSS-Prefix-Order" reports twice for prefixes order when error is in nested selectors in SASS

### ISSUE THREAD

**Issue by molant** [webhintio/hint#3037]
Create a `.scss` file with this content:

```scss
.todoapp {
	background: #fff;

	h1 {
		text-rendering: optimizeLegibility;
		-webkit-text-rendering: optimizeLegibility;
		-moz-text-rendering: optimizeLegibility;		
	}
}
```

You'll get the following on VS Code:

![image](https://user-images.githubusercontent.com/606594/65789412-3a94c500-e112-11e9-8fcc-c935fce36c57.png)

Adding an extra nested level will cause a 3rd report for the same issue:

> 'text-rendering' should be listed after '-moz-text-rendering'.
(css-prefix-order)
